# Generated by Django 3.0.7 on 2020-06-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='file',
        ),
    ]
