# Generated by Django 3.0.7 on 2020-06-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionpost', '0002_auto_20200619_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='files',
        ),
    ]
