# Generated by Django 3.0.7 on 2020-06-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionpost', '0003_auto_20200619_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
