# Generated by Django 3.0.7 on 2020-06-30 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionpost', '0004_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/', verbose_name='img'),
            preserve_default=False,
        ),
    ]
