# Generated by Django 3.0.7 on 2020-06-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognitionpost', '0005_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
